# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://www.hillert.com/"
DefaultContentLanguage  = "en"
title                   = "Gunnar Hillert"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = [""]

[outputs]
  home                  = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]

  [params.meta]
    description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    author              = "HTML5UP and Hugo"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Hillert"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "Gunnar Hillert"
    paragraph             = "Java Champion, full-stack Spring + Angular aficionado & 2019 Kona IRONMAN Finisher."
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/logo.jpg"
      shape               = "circle"
      width               = "100px"
      alt                 = "Gunnar Hillert"

  [params.sidebar]
    about               = "This is a blog of Gunnar Hillert."
    postAmount          = 3
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = true
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3
  [[menu.main]]
    name              = "Kona Coffee"
    identifier        = "coffee"
    url               = "https://coffee.hillert.com"
    pre               = "<i class='fa fa-coffee'></i>"
    weight            = 4
  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5
  [[menu.main]]
    name              = "Tags"
    identifier        = "tags"
    url               = "/tags/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 6
  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "/contact/"
    pre               = "<i class='fa fa-tags'></i>"
    weight            = 7

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.de]
    LanguageCode        = "de"
    LanguageName        = "Deutsch"
    title               = "Blog von Gunnar Hillert"
    description         = "Un thème par HTML5 UP, porté par Julio Pescador. Simplifié et amélioré par Patrick Collins. Multilingue par StatnMap. Propulsé par Hugo."
    weight              = 2

    [[Languages.de.menu.main]]
      name              = "Home"
      identifier        = "home"
      url               = "/"
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.de.menu.main]]
      name              = "Über"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.de.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.de.menu.main]]
      name              = "Kategorien"
      identifier        = "categories"
      url               = "/categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5
    [[Languages.de.menu.main]]
      name              = "Tags"
      identifier        = "tags"
      url               = "/tags/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 6
    [[Languages.de.menu.main]]
      name              = "Kontakt"
      identifier        = "contact"
      url               = "/contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 7

  [Languages.es]
    LanguageCode        = "es"
    LanguageName        = "Español"
    title               = "Hugo Future Imperfect Slim em português"
    description         = "Um tema do HTML5 UP, portado por Julio Pescadora e reduzido por Patrick Collins. Multilíngue por StatnMap. Feito com Hugo."
    weight              = 3

    [[Languages.es.menu.main]]
      name              = "Início"
      identifier        = "home"
      url               = "/"
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.es.menu.main]]
      name              = "Sobre"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.es.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.es.menu.main]]
      name              = "Categorias"
      identifier        = "categories"
      url               = "/categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 5

    [[Languages.es.menu.main]]
      name              = "Contato"
      identifier        = "contact"
      url               = "/contact/"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

[social]
  # Coding Communities
  github                = "ghillert"
  gitlab                = ""
  stackoverflow         = "" # User Number
  #bitbucket             = ""
  #jsfiddle              = ""
  #codepen               = ""
  # Visual Art Communities
  #deviantart            = ""
  #flickr                = "example"
  #behance               = ""
  #dribbble              = ""
  # Publishing Communities
  #wordpress             = ""
  #medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "hillert"
  #linkedin_company      = "examplebusiness"
  #foursquare            = ""
  xing                  = "Gunnar_Hillert"
  slideshare            = "hillert"
  # Social Networks
  #facebook              = "example"
  #googleplus            = ""
  #reddit                = "example"
  #quora                 = ""
  #youtube               = ""
  #vimeo                 = ""
  #whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
  #  wechat              = ""
  #  qq                  = "" # User ID Number
  #instagram             = "example"
  #tumblr                = ""
  twitter               = "ghillert"
  #strava                = ""
  #skype                 = ""
  #snapchat              = ""
  #pinterest             = "example"
  #telegram              = "example"
  #vine                  = ""
  #googlescholar         = ""
  #orcid                 = ""
  #researchgate          = "example"
  #keybase               = "example"
  #mastodon              = "example.com/@example"
  # Email
  email                 = "gunnar at hillert punto com"
