# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: reitzig/actions-asciidoctor@v1.0.0
      with:
        version: 2.0.10
        options: "-a experimental=true"
    - run: asciidoctor --version
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.2'
        # extended: true
    - name: Build
      run: hugo --minify
    - name: List output files
      run: ls
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.SFTP_URI }}
        ftp-username: ${{ secrets.SFTP_USERNAME }}
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        known-hosts: ${{ secrets.KNOWN_HOSTS }}
        local-dir: public # This folder is NOT going to upload by default unless you add it to .git-ftp-include
        git-ftp-args: --dry-run
